spring:
  config:
    import:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:habit66
    driver-class-name: org.h2.Driver
    username: sa
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
      default_batch_fetch_size: 1000
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  messages:
    basename: messages

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


jwt:
  access-token-validity-time: 180000 # 3?
  refresh-token-validity-time: 60480000 # 1008?
